export const moods = [
  "Funny",
  "Pain",
  "Instant Regret",
  "Fail",
  "Embarrassing",
  "Shock",
  "Rage",
  "Drama",
  "Argument",
  "Exposed",
  "Caught",
  "Scary",
  "Horror",
  "Suspense",
  "Mystery",
  "Wholesome",
  "Emotional",
  "Motivational",
  "Inspirational",
  "Underdog",
  "Comeback",
  "Clutch",
  "Skill Showcase",
  "Insane Reaction",
  "Unexpected Ending",
  "Transformation",
  "Storytime",
  "Life Lesson",
  "Relationship",
  "Flirting",
  "Rizz",
  "Challenge",
  "Prank",
  "Public Interaction",
  "Streamer Moment",
  "Podcast Moment",
  "Controversial",
  "Hot Take"
];

export const moodEmojiMap: Record<string, string[]> = {
  Funny: ["😂", "🤣", "💀"],
  Pain: ["💀", "😭"],
  "Instant Regret": ["💀", "😭", "🤦"],
  Fail: ["🤦", "💀"],
  Embarrassing: ["😳", "😭"],
  Shock: ["😱", "🤯"],
  Rage: ["🤬", "😡"],
  Drama: ["👀", "🍿"],
  Argument: ["⚔️", "🤬"],
  Exposed: ["🚨", "👀"],
  Caught: ["😳", "🚨"],
  Scary: ["😨", "😱"],
  Horror: ["👻", "😨"],
  Suspense: ["⏳", "👀"],
  Mystery: ["❓", "👀"],
  Wholesome: ["❤️", "🥹"],
  Emotional: ["😢", "❤️"],
  Motivational: ["🔥", "💪"],
  Inspirational: ["🚀", "✨"],
  Underdog: ["🏆", "💪"],
  Comeback: ["🔥", "🏆"],
  Clutch: ["🎯", "🔥"],
  "Skill Showcase": ["⚡", "🎯"],
  "Insane Reaction": ["🤯", "😱"],
  "Unexpected Ending": ["🤯", "💀"],
  Transformation: ["🚀", "✨"],
  Storytime: ["📖", "👀"],
  "Life Lesson": ["🧠", "✨"],
  Relationship: ["❤️", "😭"],
  Flirting: ["😏", "❤️"],
  Rizz: ["😎", "🔥"],
  Challenge: ["🎲", "💀"],
  Prank: ["😂", "🎭"],
  "Public Interaction": ["🌎", "👀"],
  "Streamer Moment": ["🎮", "🤣"],
  "Podcast Moment": ["🎙️", "👀"],
  Controversial: ["🚩", "👀"],
  "Hot Take": ["🔥", "🚩"]
};
